### PR TITLE
Publish metrics in seconds for session length helper

### PR DESCRIPTION
**Pull request by justinvdm**
Milliseconds will probably confused people, we should divide by `1000` when publishing the duration.

### CODE REVIEW

**Comment by justinvdm** [comment]
Depends on #133, otherwise ready for review.

**Comment by smn** [comment]
@justinvdm sweet! thanks!

**Comment by justinvdm** [comment]
Two seemingly unrelated tests were failing, but were also failing on develop:

```
  1) app for clinic use after entering the clinic code if the number used is not the mom's should save clinic code, ask for the month the baby is due:
     AssertionError: [60,66.66666666666666] deepEqual [60]
      at null.<anonymous> (/home/justin/praekelt/go-ndoh/test/clinic.test.js:952:36)
      at self.methods.check (/home/justin/praekelt/go-ndoh/node_modules/vumigo_v02/lib/tester/checks.js:142:19)
      at /home/justin/praekelt/go-ndoh/node_modules/vumigo_v02/lib/tester/tasks.js:140:23
      at /home/justin/praekelt/go-ndoh/node_modules/vumigo_v02/lib/tester/tasks.js:182:24
      at _fulfilled (/home/justin/praekelt/go-ndoh/node_modules/q/q.js:798:54)
      at self.promiseDispatch.done (/home/justin/praekelt/go-ndoh/node_modules/q/q.js:827:30)
      at Promise.promise.promiseDispatch (/home/justin/praekelt/go-ndoh/node_modules/q/q.js:760:13)
      at /home/justin/praekelt/go-ndoh/node_modules/q/q.js:526:49
      at flush (/home/justin/praekelt/go-ndoh/node_modules/q/q.js:108:17)
      at process._tickDomainCallback (node.js:403:11)

  2) app for clinic use after entering the clinic code if the number used is the mom's should save the clinic code, ask for the month the baby is due:
     AssertionError: [60,66.66666666666666] deepEqual [60]
      at null.<anonymous> (/home/justin/praekelt/go-ndoh/test/clinic.test.js:988:36)
      at self.methods.check (/home/justin/praekelt/go-ndoh/node_modules/vumigo_v02/lib/tester/checks.js:142:19)
      at /home/justin/praekelt/go-ndoh/node_modules/vumigo_v02/lib/tester/tasks.js:140:23
      at /home/justin/praekelt/go-ndoh/node_modules/vumigo_v02/lib/tester/tasks.js:182:24
      at _fulfilled (/home/justin/praekelt/go-ndoh/node_modules/q/q.js:798:54)
      at self.promiseDispatch.done (/home/justin/praekelt/go-ndoh/node_modules/q/q.js:827:30)
      at Promise.promise.promiseDispatch (/home/justin/praekelt/go-ndoh/node_modules/q/q.js:760:13)
      at /home/justin/praekelt/go-ndoh/node_modules/q/q.js:526:49
      at flush (/home/justin/praekelt/go-ndoh/node_modules/q/q.js:108:17)
      at process._tickDomainCallback (node.js:403:11)
```

**Comment by smn** [comment]
:+1:

**Comment by hodgestar** [comment]
:+1: from me too. :)

**Pull request merged**
