### PR TITLE
Update all languages option lists and load language files

### PR DESCRIPTION
**Pull request by gsvr**
Language option list: EN, AF, ZU, XH, TN, ST

Support translations on: 
- [x] Public line registration and navigation
- [x] Opt out line: 
- [x]  Service rating line

No initial translation on:
- [x] Clinic Registration
- [x] CHW line
- [x] FAQs on Public line
- [x] SMS Inbound

### CODE REVIEW

**Comment by gsvr** [comment]
@imsickofmaps 
FAQ Line has been merged into Public line.
What about SmsInbound?

**Comment by imsickofmaps** [comment]
@gsvr updated to clarify

**Comment by gsvr** [comment]
@imsickofmaps Ready for review, but we still need to load the language files once we get them.

**Comment by imsickofmaps** [comment]
:+1:

**Pull request merged**
