### PR TITLE
Prevent promise calling before Q.all

### PR DESCRIPTION
**Pull request by gsvr**

### CODE REVIEW

**Comment by gsvr** [comment]
@imsickofmaps Please review.

**Comment by imsickofmaps** [comment]
@justinvdm I think this is fine now but can you eyeball it for us to check we're not missing something? It's going to go on QA lines first anyway to check works on the live sandbox too. Note: Look at the last file in the PR, the others are compiled.

**Comment by justinvdm** [comment]
Looks good to me :)

**Comment by imsickofmaps** [comment]
:+1:

**Pull request merged**
