### PR TITLE
Add FAQ Metrics to Global Dashboard

### PR DESCRIPTION
**Pull request by gsvr**

### CODE REVIEW

**Comment by gsvr** [comment]
@imsickofmaps Please review.  You can look at the production dashboard to see changes:
https://go.vumi.org/conversations/fa3253f4a7c7414b9498ef5052a89be1/reports/

**Comment by imsickofmaps** [comment]
@gsvr Travis is failing... can you check why?

**Comment by imsickofmaps** [comment]
Land #120 and merge develop into the open PR's to make Travis happy?

**Comment by gsvr** [comment]
@imsickofmaps Travis is happy now.

**Comment by imsickofmaps** [comment]
:+1:

**Pull request merged**
