### PR TITLE
Implement dial-back restart

### PR DESCRIPTION
**Pull request by gsvr**

### CODE REVIEW

**Comment by gsvr** [comment]
@imsickofmaps About to start adding to CHW and Clinic lines.  Review this part in the meantime if you'd like to for expediency.

Note that there's a failing test I'm battling with.  Would appreciate your input on it - I commented out the code in personal.js that I tried.

**Comment by gsvr** [comment]
@imsickofmaps Implemented on clinic and chw lines.  Personal line needs a fix.

**Comment by gsvr** [comment]
:+1:

**Comment by imsickofmaps** [comment]
@gsvr try again, with more commits :grinning:

**Pull request merged**
