### PR TITLE
Metrics and Jembi api response handling

### PR DESCRIPTION
**Pull request by gsvr**
Need to know what their response is going to be in good/bad
- [x] Number of completed clinic registrations sent to HIE from Clinic Line - Total and over time
- [x] Number of complete suspected pregnancy registrations sent to HIE from CHW line - Total and over time
- [x] Number of complete subscriptions sent to HIE  from the public line - Total and over time

### CODE REVIEW

**Comment by gsvr** [comment]
@imsickofmaps Please review

**Comment by imsickofmaps** [comment]
@smn reviewed by me, ready when you are.

**Comment by smn** [comment]
:+1:

**Pull request merged**
