### PR TITLE
Remove QA configs from repo

### PR DESCRIPTION
**Pull request by gsvr**
Moving to the private repo: See https://github.com/praekelt/go-ndoh-private/pull/17

### CODE REVIEW

**Comment by gsvr** [comment]
@imsickofmaps Please review.

**Comment by imsickofmaps** [comment]
Lets leave them as it's OSS, but rename to .example

**Comment by gsvr** [comment]
@imsickofmaps :+1: ?

**Comment by imsickofmaps** [comment]
:+1:

**Pull request merged**
