### PR TITLE
Some tests fail in isolation

### PR DESCRIPTION
**Pull request by gsvr**
```
$ grunt mochaTest:test_smsinbound
Running "mochaTest:test_smsinbound" (mochaTest) task


  app
    for sms inbound use
      using the session length helper
        ✓ should publish metrics (86ms)
      when a new unique user sends message in
        ✓ should increment the no. of unique users by 1 (72ms)
      when the user sends a non standard keyword message
        ✓ should log a support ticket (76ms)
      when the user sends a message containing a USSD code
        ✓ should tell them to dial the number, not sms it (70ms)
      when the user sends a STOP message
        1) should set their opt out status
      when the user sends a BLOCK message
        2) should set their opt out status
      when the user sends a START message
        ✓ should reverse their opt out status (58ms)
      when the user sends a BABY message
        ✓ should switch their subscription to baby protocol (90ms)


  6 passing (596ms)
  2 failing

  1) app for sms inbound use when the user sends a STOP message should set their opt out status:
     ReferenceError: opts is not defined
      at /Users/sdehaan/Documents/Repositories/go-ndoh/src/smsinbound.js:79:90
      at _fulfilled (/Users/sdehaan/Documents/Repositories/go-ndoh/node_modules/q/q.js:798:54)
      at self.promiseDispatch.done (/Users/sdehaan/Documents/Repositories/go-ndoh/node_modules/q/q.js:827:30)
      at Promise.promise.promiseDispatch (/Users/sdehaan/Documents/Repositories/go-ndoh/node_modules/q/q.js:760:13)
      at /Users/sdehaan/Documents/Repositories/go-ndoh/node_modules/q/q.js:574:44
      at flush (/Users/sdehaan/Documents/Repositories/go-ndoh/node_modules/q/q.js:108:17)
      at process._tickDomainCallback (node.js:459:13)

  2) app for sms inbound use when the user sends a BLOCK message should set their opt out status:
     ReferenceError: opts is not defined
      at /Users/sdehaan/Documents/Repositories/go-ndoh/src/smsinbound.js:79:90
      at _fulfilled (/Users/sdehaan/Documents/Repositories/go-ndoh/node_modules/q/q.js:798:54)
      at self.promiseDispatch.done (/Users/sdehaan/Documents/Repositories/go-ndoh/node_modules/q/q.js:827:30)
      at Promise.promise.promiseDispatch (/Users/sdehaan/Documents/Repositories/go-ndoh/node_modules/q/q.js:760:13)
      at /Users/sdehaan/Documents/Repositories/go-ndoh/node_modules/q/q.js:574:44
      at flush (/Users/sdehaan/Documents/Repositories/go-ndoh/node_modules/q/q.js:108:17)
      at process._tickDomainCallback (node.js:459:13)



Warning: Task "mochaTest:test_smsinbound" failed. Use --force to continue.

Aborted due to warnings.
```

Which is correct because [`opts`](https://github.com/praekelt/go-ndoh/blob/develop/src/smsinbound.js#L77) is not defined anywhere, it's likely that your tests are leaking variables somewhere which means this bit of code manages to grab some `opts` value from somewhere.

### CODE REVIEW

**Comment by gsvr** [comment]
@imsickofmaps Please review.

**Comment by imsickofmaps** [comment]
:+1:

**Pull request closed without merging**
